import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";
import "./styles/motion.css";
import "./styles/admin.css";
import "./styles/buttons.css";
import "./styles/theme.css";
import "./styles/3d-effects.css";
ReactDOM.createRoot(document.getElementById("root")).render(<React.StrictMode><App /></React.StrictMode>);
