import { useEffect, useMemo, useState } from "react";
import "./ActivityMonitor.css";
const API_URL=import.meta.env.VITE_API_URL||"http://localhost:5000";
export default function ActivityMonitor(){
 const [activities,setActivities]=useState([]),[tasks,setTasks]=useState([]),[submissions,setSubmissions]=useState([]),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[loading,setLoading]=useState(true);
 const load=async()=>{const h={Authorization:`Bearer ${localStorage.getItem("token")}`};try{const [a,b,c]=await Promise.all([fetch(`${API_URL}/api/activities`,{headers:h}),fetch(`${API_URL}/api/tasks`,{headers:h}),fetch(`${API_URL}/api/tasks/submissions`,{headers:h})]);const [ad,td,sd]=await Promise.all([a.json(),b.json(),c.json()]);setActivities(ad.activities||[]);setTasks(td.tasks||[]);setSubmissions(sd.submissions||[])}finally{setLoading(false)}};
 useEffect(()=>{load();const id=setInterval(load,20000);return()=>clearInterval(id)},[]);
 const today=new Date().toISOString().slice(0,10);const todayUpdates=activities.filter(a=>a.date===today).length;const completed=tasks.filter(t=>t.status==='completed').length;const pending=tasks.filter(t=>t.status!=='completed').length;
 const filtered=useMemo(()=>activities.filter(a=>{const q=search.toLowerCase();const matches=`${a.student_name} ${a.work_title} ${a.description}`.toLowerCase().includes(q);const status=filter==='all'||a.status===filter;return matches&&status}),[activities,search,filter]);
 return <div className="manager-page page-enter"><div className="simple-head"><span>TEAM MONITOR</span><h2>Activity command center</h2><p>Monitor daily updates, task progress and submitted student work.</p></div><div className="manager-stats"><div><span>Total activities</span><strong>{activities.length}</strong></div><div><span>Today updates</span><strong>{todayUpdates}</strong></div><div><span>Completed tasks</span><strong>{completed}</strong></div><div><span>Pending tasks</span><strong>{pending}</strong></div></div>
 <div className="panel"><div className="panel-head"><div><span className="section-kicker">DAILY TEAM ACTIVITIES</span><h3>Live activity feed</h3></div><div className="monitor-tools"><input className="search-input" placeholder="Search member or activity" value={search} onChange={e=>setSearch(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All status</option><option value="completed">Completed</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option></select><button onClick={load}>Refresh</button></div></div>{loading&&!activities.length?<div className="empty-state">Syncing activity…</div>:filtered.map(a=><article className="activity-admin" key={a.id}><div className="avatar">{(a.student_name||'S').charAt(0)}</div><div><strong>{a.student_name}</strong><h4>{a.work_title}</h4><p>{a.description}</p><small>{a.date} · {a.hours_worked||0} hours · {a.status}</small></div></article>)}{!filtered.length&&<div className="empty-state">No matching activity.</div>}</div>
 <div className="panel"><div className="panel-head"><div><span className="section-kicker">SUBMITTED WORK</span><h3>Student reports & files</h3></div></div>{submissions.length?submissions.map(item=><div className="submission-manager" key={item.id}><div><strong>{item.title}</strong><small>{item.student_name} · {item.file_count||0} file{item.file_count===1?'':'s'} · {item.outcome?'Outcome submitted':'File submitted'}</small>{item.outcome&&<p>{item.outcome}</p>}</div><span className="pill completed">{item.status}</span></div>):<div className="empty-state">No submitted work yet.</div>}</div>
 </div>
}
